apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactolatry-deployment
  labels:
    app: reactolatry
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactolatry
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 34%
      maxUnavailable: 34%
  template:
    metadata:
      name: reactolatry
      labels:
        app: reactolatry
    spec:
      containers:
      - name: reactolatry
        image: darylwalsh/reactolatryfe:0.1.3
        imagePullPolicy: IfNotPresent
        env:
          - name: APP_HOST
            value: reactolatry.io
          - name: DB_URL
            value: ecto://postgres:postgres@db/reactolatry_prod
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PORT
            value: "4000"
          - name: RELEASE_COOKIE
            value: reactolatry-secret-cookie
          - name: SECRET_KEY_BASE
            value: super-secret-key-base
          - name: SERVICE_NAME
            value: reactolatry.default.svc.cluster.local
        resources: {}
        securityContext:
          privileged: false
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
